import mongoose from "mongoose";

const postSchema = new mongoose.Schema({
  userID: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  providerID: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Provider",
    required: true,
  },
  providerType: {
    type: String,
    enum: ["private", "ngo"],
    required: true,
    trim: true,
    lowercase: true,
  },
  title: { type: String, required: true },
  description: { type: String, required: true },
  serviceType: {
    type: [String],
    enum: [
      "Food",
      "Personal Meal Preparation",
      "Meal Delivery",
      "Event Catering",
      "Holiday Meal Assistance",
      "Food for Special Diets",

      "Household Help",
      "House Cleaning",
      "Furniture Moving",
      "Organization and Decluttering",
      "Laundry Assistance",
      "Gardening",

      "Plumbing Services",
      "Leak Repair",
      "Pipe Installation",
      "Drain Cleaning",
      "Bathroom Installation",
      "Water Heater Repair",

      "Education",
      "Tutoring",
      "Test Preparation",
      "Language Learning",
      "Skill Development",
      "Online Courses",

      "Emotional Support",
      "Counseling",
      "Therapy",
      "Grief Support",
      "Peer Support",
      "Mental Health Resources",

      "Repairs & Maintenance",
      "Electrical Repairs",
      "Appliance Repairs",
      "Home Maintenance",
      "HVAC Services",
      "Painting & Touch-ups",

      "Pet Care",
      "Dog Walking",
      "Pet Sitting",
      "Pet Grooming",
      "Veterinary Assistance",
      "Pet Training",

      "Childcare",
      "Babysitting",
      "Nanny Services",
      "Childhood Education",
      "Special Needs Assistance",
      "After-School Care",

      "Transportation",
      "Car Pooling",
      "Delivery Services",
      "Taxi Services",
      "Bike Rentals",
      "Ride Sharing",

      "Legal Services",
      "Legal Consultation",
      "Contract Review",
      "Family Law",
      "Criminal Defense",
      "Intellectual Property",

      "Health & Fitness",
      "Personal Training",
      "Yoga Classes",
      "Nutrition Advice",
      "Mental Wellness",
      "Group Fitness",

      "Event Planning",
      "Wedding Planning",
      "Birthday Party Coordination",
      "Corporate Events",
      "Conference Organizing",
      "Festival Planning",

      "Volunteer Work",
      "Community Outreach",
      "Environmental Initiatives",
      "Charity Events",
      "Elderly Care",
      "Homeless Shelter Support",

      "Technology Support",
      "IT Support",
      "Software Installation",
      "Website Development",
      "Cybersecurity",
      "Device Repair",

      "Creative Services",
      "Graphic Design",
      "Video Production",
      "Photography",
      "Writing & Editing",
      "Social Media Management",

      "Assistance for Soldiers",
      "Military Housing Assistance",
      "Veteran Care",
      "Military Legal Assistance",
      "Job Placement for Veterans",
      "Support for Active Duty",

      "Construction & Renovation",
      "Home Construction",
      "Kitchen Renovation",
      "Bathroom Renovation",
      "Roof Repair",
      "General Contracting",

      "Cleaning Services",
      "Carpet Cleaning",
      "Window Cleaning",
      "Pressure Washing",
      "Deep Cleaning",
      "Office Cleaning",

      "Gardening & Landscaping",
      "Lawn Care",
      "Landscape Design",
      "Tree Trimming",
      "Irrigation Systems",
      "Garden Maintenance",
    ],
    required: true,
  },
  status: {
    type: [String],
    enum: [
      "Single mother",
      "Single father",
      "Active-duty soldier",
      "Reservist",
      "Undergraduate student",
      "Graduate student",
      "Doctoral student",
      "Person with a physical disability",
      "Person with a mental disability",
      "Retiree",
      "Pensioner",
      "New immigrant",
      "Returning resident",
      "Unemployment benefits recipient",
      "Part-time worker",
      "Minority group member",
    ],
    required: true,
  },
  location: {
    type: [String],
    enum: [
      "North",
      "Central",
      "South",
      "Jerusalem and Surroundings",
      "Negev",
      "Shfela (Lowland)",
      "Sharon",
      "Coastal Plain",
      "Golan Heights",
      "Galilee",
    ],
    required: true,
  },

  createdAt: { type: Date, default: Date.now },
});

export default mongoose.model("Post", postSchema);
